"""Writes the canonical site→property mapping consumed by the data-hub collector."""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

from .discover import Property

REGISTRY_PATH = Path(
    "/home/jesse/projects/domains/tools/data-hub/registry/sites-analytics.yaml"
)

# GA4 loads only after explicit consent on these sites, so their numbers
# undercount real traffic and must never be ranked against ungated sites.
CONSENT_GATED = {"saveusfarms.com", "weapontester.com", "allthingsmasonic.com",
                 "fishhooklabs.com", "shoptopless.com"}

HEADER = (
    "# Canonical site -> GA4 property / GSC property mapping.\n"
    "# Generated by tools/ga4-provision. Do not hand-edit.\n"
    "# consent_gated sites report only consented traffic (undercount).\n"
)


def build_registry(
    properties: list[Property],
    measurement_map: dict[str, str],
    consent_gated: set[str] | None = None,
) -> dict:
    """Map discovered properties to the registry shape.

    A site with no known measurement ID gets None, not "" — absence must stay
    distinguishable from a real value.
    """
    gated = CONSENT_GATED if consent_gated is None else consent_gated
    sites: dict[str, dict] = {}

    # Sort ascending by property_id so a display_name collision deterministically
    # keeps the highest (most-recently-created) property, regardless of API
    # response ordering. Confirmed correct in practice for the one known
    # collision (0daynews.com 543877193 vs 544645637): the newer property's
    # measurement ID is the one actually embedded in the site's source.
    for prop in sorted(properties, key=lambda p: (p.display_name, int(p.property_id))):
        site = prop.display_name.strip()
        if not site:
            continue
        if site in sites:
            print(
                f"WARNING: duplicate GA4 display_name {site!r} — "
                f"property {sites[site]['ga4_property_id']} overwritten by "
                f"newer property {prop.property_id} (highest property_id wins)",
                file=sys.stderr,
            )
        sites[site] = {
            "ga4_property_id": prop.property_id,
            "ga4_measurement_id": (measurement_map.get(site) or "").strip() or None,
            "gsc_property": f"sc-domain:{site}",
            "consent_gated": site in gated,
        }

    return {"sites": sites}


def write_registry(data: dict, path: Path | None = None) -> None:
    """Write the registry YAML, creating parent dirs as needed."""
    target = Path(path) if path else REGISTRY_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(data, sort_keys=False, default_flow_style=False)
    target.write_text(HEADER + body)
