'use strict';

// The CRO repo lab evaluates public repositories in a disposable, read-only
// container. It is deliberately separate from the site improvement sandbox:
// a candidate repository is evidence, not fleet code, and can never receive a
// project checkout, credentials, Docker socket, or production access.

const crypto = require('node:crypto');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync } = require('node:child_process');

const MAX_ARCHIVE_BYTES = 40 * 1024 * 1024;
const MAX_TEXT_BYTES = 120 * 1024;
const MAX_FILES = 5000;
const MAX_CHECK_FILES = 8;
const MAX_REPORTS = 100;
const CHECK_TIMEOUT_MS = 30_000;
const DEFAULT_IMAGE = process.env.CRO_LAB_IMAGE || 'domain-developer:latest';
const GITHUB_RE = /^https:\/\/github\.com\/([A-Za-z0-9_.-]+)\/([A-Za-z0-9_.-]+?)(?:\.git)?\/?$/;

function httpError(message, status = 400) {
  const error = new Error(message);
  error.httpStatus = status;
  return error;
}

function candidateSlug(candidate) {
  const value = String(candidate?.full_name || '').trim();
  const parts = value.split('/');
  if (
    parts.length !== 2 ||
    parts.some(part => !/^[A-Za-z0-9_.-]+$/.test(part) || part === '.' || part === '..')
  )
    throw httpError('invalid GitHub candidate');
  return value;
}

function githubUrl(candidate) {
  const value = String(candidate?.html_url || `https://github.com/${candidateSlug(candidate)}`).trim();
  const match = value.match(GITHUB_RE);
  if (!match || `${match[1]}/${match[2]}`.toLowerCase() !== candidateSlug(candidate).toLowerCase())
    throw httpError('CRO candidates must be canonical public GitHub repositories');
  return `https://github.com/${match[1]}/${match[2]}`;
}

function archiveUrl(candidate) {
  const slug = candidateSlug(candidate);
  return `https://codeload.github.com/${slug}/tar.gz/${encodeURIComponent(String(candidate.default_branch || 'HEAD'))}`;
}

async function downloadArchive(candidate, fetchImpl = globalThis.fetch) {
  const url = archiveUrl(candidate);
  const parsed = new URL(url);
  if (parsed.protocol !== 'https:' || parsed.hostname !== 'codeload.github.com')
    throw new Error('CRO archive must use codeload.github.com over HTTPS');
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 30_000);
  try {
    const response = await fetchImpl(url, {
      signal: controller.signal,
      headers: { 'user-agent': 'domains-cro-repo-lab/1.0', accept: 'application/octet-stream' },
    });
    if (!response.ok) throw new Error(`GitHub archive returned HTTP ${response.status}`);
    const length = Number(response.headers?.get?.('content-length') || 0);
    if (length > MAX_ARCHIVE_BYTES) throw new Error('repository archive exceeds CRO lab size limit');
    if (typeof response.arrayBuffer !== 'function') throw new Error('GitHub archive response is not binary');
    const buffer = Buffer.from(await response.arrayBuffer());
    if (buffer.length > MAX_ARCHIVE_BYTES) throw new Error('repository archive exceeds CRO lab size limit');
    return { url, buffer };
  } finally {
    clearTimeout(timer);
  }
}

function extractArchive(archivePath, repoDir) {
  fs.mkdirSync(repoDir, { recursive: true, mode: 0o700 });
  // GNU tar strips the single GitHub archive directory. The output directory
  // is generated by this module and is never a project path.
  execFileSync('tar', [
    '--extract',
    '--gzip',
    '--file',
    archivePath,
    '--directory',
    repoDir,
    '--strip-components=1',
    '--no-same-owner',
    '--no-same-permissions',
  ], { timeout: 30_000, stdio: 'pipe' });
}

function readText(file, maxBytes = MAX_TEXT_BYTES) {
  try {
    const stat = fs.lstatSync(file);
    if (!stat.isFile() || stat.size > maxBytes) return '';
    return fs.readFileSync(file, 'utf8').slice(0, maxBytes);
  } catch {
    return '';
  }
}

function listFiles(root, current = root, depth = 0, output = []) {
  if (output.length >= MAX_FILES || depth > 5) return output;
  let entries;
  try {
    entries = fs.readdirSync(current, { withFileTypes: true });
  } catch {
    return output;
  }
  for (const entry of entries) {
    if (output.length >= MAX_FILES) break;
    if (entry.name === '.git' || entry.name === 'node_modules' || entry.name === '.venv') continue;
    const full = path.join(current, entry.name);
    if (entry.isDirectory()) listFiles(root, full, depth + 1, output);
    else if (entry.isFile()) output.push(path.relative(root, full).replaceAll(path.sep, '/'));
  }
  return output;
}

function readRepoManifest(repoDir, files) {
  let packageJson = null;
  try {
    packageJson = JSON.parse(readText(path.join(repoDir, 'package.json')) || 'null');
  } catch {
    packageJson = null;
  }
  const readmes = files.filter(file => /(^|\/)(readme|contributing|security)(?:\.|$)/i.test(file)).slice(0, 4);
  const docs = readmes.map(file => ({ file, text: readText(path.join(repoDir, file), 40 * 1024) }));
  const sourceFiles = files.filter(file => /\.(?:js|jsx|mjs|cjs|ts|tsx|py|go|rs|astro|vue|svelte)$/.test(file));
  return {
    file_count: files.length,
    files: files.slice(0, 300),
    package: packageJson
      ? {
          name: packageJson.name || null,
          version: packageJson.version || null,
          license: packageJson.license || null,
          scripts: packageJson.scripts || {},
          dependencies: Object.keys({ ...(packageJson.dependencies || {}), ...(packageJson.devDependencies || {}) }).slice(0, 100),
        }
      : null,
    docs,
    source_files: sourceFiles.slice(0, MAX_CHECK_FILES),
    has_lockfile: files.some(file => /(^|\/)(package-lock\.json|pnpm-lock\.yaml|yarn\.lock|poetry\.lock|uv\.lock|go\.sum)$/.test(file)),
    has_dependency_tree: files.some(file => /(^|\/)node_modules\//.test(file) || /(^|\/)\.venv\//.test(file)),
  };
}

function purposeEvidence(candidate, manifest) {
  const purpose = String(candidate.purpose || 'measurement');
  const corpus = [
    candidate.description || '',
    ...(candidate.topics || []),
    ...(manifest.docs || []).map(row => row.text),
    JSON.stringify(manifest.package || {}),
  ].join('\n');
  const patterns = {
    conversion: /conversion|experiment|feature.?flag|funnel|ab.?test|growth/i,
    seo_content: /seo|sitemap|structured.?data|schema\.org|cms|markdown|publishing|editorial/i,
    platform_ux: /astro|cloudflare|worker|edge|accessibility|tailwind|frontend|vite/i,
    measurement: /analytics|attribution|telemetry|affiliate|ecommerce|event.?tracking|product.?feed/i,
  };
  const matcher = patterns[purpose] || patterns.measurement;
  const matches = (corpus.match(new RegExp(matcher.source, 'gi')) || []).length;
  const evidence = (manifest.docs || [])
    .filter(row => patterns[purpose]?.test(row.text))
    .map(row => row.file)
    .slice(0, 5);
  return {
    purpose,
    question: `Can this repository produce a measurable ${purpose.replaceAll('_', ' ')} outcome for the fleet?`,
    keyword_hits: matches,
    documentation_files: evidence,
    fit: matches >= 3 ? 'supported' : matches > 0 ? 'weak' : 'unverified',
    note:
      matches >= 3
        ? 'The repository documentation and package metadata contain purpose-specific capability signals.'
        : 'Public metadata does not yet establish a concrete fleet use case; a human should not adopt it on popularity alone.',
  };
}

function shellQuote(value) {
  return `'${String(value).replaceAll("'", "'\\''")}'`;
}

function sandboxBase(workspace, image, name) {
  return [
    'run', '--rm', '--name', name,
    '--read-only', '--cap-drop=ALL', '--security-opt=no-new-privileges',
    '--pids-limit=128', '--memory=768m', '--cpus=1',
    '--tmpfs', '/tmp:rw,noexec,nosuid,size=64m', '--network=none',
    '--workdir', '/workspace/repo', '-v', `${workspace}:/workspace/repo:ro`,
    image,
  ];
}

function dockerSandbox({ workspace, commands, image = DEFAULT_IMAGE, name = `cro-lab-${crypto.randomUUID()}` }) {
  const checks = [];
  for (const [index, command] of commands.entries()) {
    const started = Date.now();
    try {
      const stdout = execFileSync('docker', [...sandboxBase(workspace, image, `${name}-${index}`), 'sh', '-lc', command], {
        timeout: CHECK_TIMEOUT_MS,
        maxBuffer: 64 * 1024,
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'pipe'],
      });
      checks.push({ command, status: 'passed', duration_ms: Date.now() - started, output: String(stdout).slice(-12_000) });
    } catch (error) {
      const message = `${error.stdout || ''}${error.stderr || ''}`.slice(-12_000);
      checks.push({
        command,
        status: error.status === undefined ? 'unavailable' : 'failed',
        duration_ms: Date.now() - started,
        output: message || error.message,
      });
    }
  }
  return checks;
}

function checkCommands(manifest) {
  const commands = [];
  for (const file of manifest.source_files || []) {
    if (/\.(?:js|jsx|mjs|cjs)$/.test(file)) commands.push(`node --check ${shellQuote(`/workspace/repo/${file}`)}`);
    else if (/\.py$/.test(file)) commands.push(`python3 -m py_compile ${shellQuote(`/workspace/repo/${file}`)}`);
    if (commands.length >= MAX_CHECK_FILES) break;
  }
  // Deliberately do not install or execute package-manager dependencies. If a
  // candidate arrives with a vendored dependency tree, the report still
  // records that fact for a later owner-approved security review instead of
  // silently running arbitrary lifecycle scripts.
  return commands;
}

function recommendation(manifest, useCase, checks, candidate) {
  const license = candidate.license_spdx_id || manifest.package?.license || null;
  const passed = checks.filter(row => row.status === 'passed').length;
  const failed = checks.filter(row => row.status === 'failed').length;
  if (!license) return { decision: 'hold', reason: 'License is not reported; legal review is required before adoption.' };
  if (useCase.fit === 'unverified') return { decision: 'hold', reason: 'The repository does not establish a concrete fleet use case.' };
  if (failed) return { decision: 'hold', reason: `${failed} bounded syntax check(s) failed; CTO review is required.` };
  if (!passed && !checks.length) return { decision: 'research', reason: 'No safe native checks were available without installing dependencies.' };
  return {
    decision: 'research',
    reason: 'The candidate has a plausible use case and passed the available bounded checks, but adoption still requires a fleet-specific prototype, security review, and owner-approved change.',
  };
}

async function runCandidate({
  candidate,
  fetchImpl = globalThis.fetch,
  runSandbox = dockerSandbox,
  downloadArchiveImpl = downloadArchive,
  extractArchiveImpl = extractArchive,
  root,
  now = new Date(),
} = {}) {
  const slug = candidateSlug(candidate);
  const repoUrl = githubUrl(candidate);
  const runId = crypto.randomUUID();
  // When CRO runs inside fleet-cron, /tmp belongs to that container while the
  // Docker daemon resolves bind mounts on the host. Keeping this one ignored,
  // disposable directory under the shared repo gives both sides the same
  // path without mounting the project into the lab.
  const workspaceParent = root
    ? path.join(root, 'tools', 'executive', 'data', '.cro-lab-workspaces')
    : os.tmpdir();
  fs.mkdirSync(workspaceParent, { recursive: true, mode: 0o700 });
  const workspace = fs.mkdtempSync(path.join(workspaceParent, 'run-'));
  const repoDir = path.join(workspace, 'repo');
  const report = {
    schema: 'cro-repo-lab/v1',
    run_id: runId,
    generated_at: now.toISOString(),
    candidate: { full_name: slug, html_url: repoUrl, purpose: candidate.purpose || null },
    workspace: { ephemeral: true, project_mounts: [], secrets: false, docker_socket: false, network: 'none during checks' },
    source: { archive_url: archiveUrl(candidate), ref: candidate.default_branch || 'HEAD' },
    status: 'failed',
  };
  try {
    const archive = await downloadArchiveImpl(candidate, fetchImpl);
    const archivePath = path.join(workspace, 'source.tar.gz');
    fs.writeFileSync(archivePath, archive.buffer, { mode: 0o600 });
    extractArchiveImpl(archivePath, repoDir);
    const files = listFiles(repoDir);
    const manifest = readRepoManifest(repoDir, files);
    const useCase = purposeEvidence(candidate, manifest);
    const commands = checkCommands(manifest);
    const checks = await runSandbox({ workspace: repoDir, commands });
    report.repository = {
      ...manifest,
      license: candidate.license_spdx_id || manifest.package?.license || null,
    };
    report.use_case = useCase;
    report.checks = checks;
    report.safety = {
      dependency_install: 'not_performed',
      production_access: false,
      recommendation_gate: 'prototype and owner approval required before adoption',
    };
    report.recommendation = recommendation(manifest, useCase, checks, candidate);
    report.status = checks.some(row => row.status === 'unavailable') ? 'partial' : 'completed';
  } catch (error) {
    report.error = String(error.message || error);
    report.recommendation = { decision: 'blocked', reason: report.error };
  } finally {
    fs.rmSync(workspace, { recursive: true, force: true });
  }
  if (root) persist(root, report);
  return report;
}

function persist(root, report) {
  const dir = path.join(root, 'tools', 'executive', 'data', 'cro-lab');
  fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
  const file = path.join(dir, `${report.run_id}.json`);
  const temp = `${file}.${process.pid}.tmp`;
  fs.writeFileSync(temp, JSON.stringify(report, null, 2) + '\n', { mode: 0o600 });
  fs.renameSync(temp, file);
  const retained = fs
    .readdirSync(dir)
    .filter(name => /^[0-9a-f-]{36}\.json$/i.test(name))
    .sort()
    .reverse();
  for (const old of retained.slice(MAX_REPORTS)) {
    try {
      fs.unlinkSync(path.join(dir, old));
    } catch {
      // A concurrent read or cleanup must not make the CRO run fail.
    }
  }
  return file;
}

function read(root, id) {
  if (!/^[0-9a-f-]{36}$/i.test(String(id))) return null;
  try {
    return JSON.parse(fs.readFileSync(path.join(root, 'tools', 'executive', 'data', 'cro-lab', `${id}.json`), 'utf8'));
  } catch {
    return null;
  }
}

function recent(root, limit = 20) {
  const dir = path.join(root, 'tools', 'executive', 'data', 'cro-lab');
  try {
    return fs.readdirSync(dir).filter(file => /^[0-9a-f-]{36}\.json$/i.test(file)).map(file => {
      try { return JSON.parse(fs.readFileSync(path.join(dir, file), 'utf8')); } catch { return null; }
    }).filter(Boolean).sort((a, b) => String(b.generated_at).localeCompare(String(a.generated_at))).slice(0, Math.min(100, Math.max(1, Number(limit) || 20)));
  } catch {
    return [];
  }
}

module.exports = {
  MAX_ARCHIVE_BYTES,
  archiveUrl,
  candidateSlug,
  githubUrl,
  purposeEvidence,
  checkCommands,
  downloadArchive,
  runCandidate,
  persist,
  read,
  recent,
  dockerSandbox,
};
