#!/usr/bin/env python3
"""Push registry/fleet.yaml outward into the rosters that still own their own list.

Phase 2 half-step: the consumers have not been migrated to read the registry
directly yet (that's a reviewed, per-consumer change). Until they are, this
keeps their lists in sync from the registry so a site can never again be live
but invisible to a tool.

ADDITIVE ONLY. It appends missing sites with sane defaults and never edits or
removes an existing entry — hand-tuned per-site config stays untouched.

    sync_rosters.py                # dry run: show what would be added
    sync_rosters.py --apply        # write it

Targets:
  tools/site-tracker/sites.yml     — feeds site-tracker AND gh-stats

Deliberately NOT synced:
  data-hub/sites-analytics.yaml    — generated by ga4-provision; a missing site
                                     needs a real GA4 property, not a stub row.
                                     Run the ga4-admin skill instead.
  */subscriptions.yaml             — opt-in, needs a human to pick tags.
  DOMAINS_INDEX.md                 — prose/TLDR column is human-owned.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
import fleet_registry as R  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
TRACKER = ROOT / "tools" / "site-tracker" / "sites.yml"

# The check set site-tracker applies to a normal fleet site. Mirrors what the
# existing full-coverage entries (e.g. amputeenews.com) declare.
DEFAULT_APPLIES_TO = [
    "cf", "http", "seo", "sitemap", "tls", "git", "ops",
    "github", "ads", "contact", "legal", "branding", "manual",
]


def plan_tracker(registry: dict) -> dict[str, dict]:
    """Entries site-tracker is missing, built from the registry."""
    data = yaml.safe_load(TRACKER.read_text(encoding="utf-8")) or {}
    have = data.get("sites") or {}
    additions: dict[str, dict] = {}
    for domain, entry in sorted(registry.items()):
        if domain in have:
            continue
        if entry.get("status") not in ("live", "scaffold"):
            continue  # parked/redirect domains are not site-tracker's business
        if not entry.get("repo"):
            continue  # no repo = nothing for the git/github checks to read
        additions[domain] = {
            "active": entry.get("status") == "live",
            "cf_zone": entry.get("cf_zone", domain),
            "github": entry["repo"],
            "applies_to": list(DEFAULT_APPLIES_TO),
            "manual": {},
        }
    return additions


def apply_tracker(additions: dict[str, dict]) -> None:
    data = yaml.safe_load(TRACKER.read_text(encoding="utf-8")) or {}
    data.setdefault("sites", {}).update(additions)
    TRACKER.write_text(
        yaml.safe_dump(data, sort_keys=False, width=100, allow_unicode=True),
        encoding="utf-8",
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--apply", action="store_true", help="write the changes")
    args = ap.parse_args()

    registry = R.load(fresh=True)
    additions = plan_tracker(registry)

    if not additions:
        print("site-tracker/sites.yml: already covers every live/scaffold site")
        return 0

    print(f"site-tracker/sites.yml: {len(additions)} site(s) to add")
    for domain, entry in additions.items():
        print(f"  + {domain}  (active={entry['active']}, repo={entry['github']})")

    if args.apply:
        apply_tracker(additions)
        print(f"\nwrote {TRACKER.relative_to(ROOT)} — review the diff before committing")
    else:
        print("\ndry run — re-run with --apply to write")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
